[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
    'dotnet restore',
    'dotnet publish Fulbito.Api/Fulbito.Api.csproj -c Release -o out --no-restore'
]

[start]
cmd = 'cd out && dotnet Fulbito.Api.dll --urls "http://0.0.0.0:$PORT"'