// <auto-generated />
using System;
using GestionLigas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionLigas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250903161426_InitialCrearLiga")]
    partial class InitialCrearLiga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionLigas.Features.CrearLiga.ConfiguracionLiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ArqueroObligatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadMinimaArqueros")
                        .HasColumnType("integer");

                    b.Property<string>("DiasJuego")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Horarios")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LigaId")
                        .HasColumnType("integer");

                    b.Property<string>("PosicionesDisponibles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReglasAdicionales")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LigaId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesLiga");
                });

            modelBuilder.Entity("GestionLigas.Features.CrearLiga.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("GestionLigas.Features.CrearLiga.ConfiguracionLiga", b =>
                {
                    b.HasOne("GestionLigas.Features.CrearLiga.Liga", "Liga")
                        .WithOne("Configuracion")
                        .HasForeignKey("GestionLigas.Features.CrearLiga.ConfiguracionLiga", "LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("GestionLigas.Features.CrearLiga.Liga", b =>
                {
                    b.Navigation("Configuracion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
